config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :api_access_allowed_ips, except: [:show, :edit, :update]
  resources :transports, except: [:show]
  resources :attachments_encryption_disable_domain_tos, except: [:show]
  resources :attachments_encryption_disable_domain_froms, except: [:show]
  resources :attachments_encryption_disable_emails, except: [:show]
  resources :bcc_conversion_disable_domains, except: [:show]
  root to: 'settings#index'
  resources :settings, only: [:create]
  get '/api/v1/setting.json', to: 'settings#index_api_v1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transport.rb
class Transport < ApplicationRecord
  validates_presence_of :domain, :nexthop
  validates :port, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 65536 }
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transport, only: [:edit, :update, :destroy]

  # GET /transports
  # GET /transports.json
  def index
    @transports = Transport.all
  end

  # GET /transports/new
  def new
    @transport = Transport.new
  end

  # GET /transports/1/edit
  def edit
  end

  # POST /transports
  # POST /transports.json
  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html { redirect_to transports_url, notice: 'Transport was successfully created.' }
        format.json { render :show, status: :created, location: @transport }
      else
        format.html { render :new }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transports/1
  # PATCH/PUT /transports/1.json
  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to transports_url, notice: 'Transport was successfully updated.' }
        format.json { render :show, status: :ok, location: @transport }
      else
        format.html { render :edit }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transports/1
  # DELETE /transports/1.json
  def destroy
    @transport.destroy
    respond_to do |format|
      format.html { redirect_to transports_url, notice: 'Transport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport
      @transport = Transport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transport_params
      params.require(:transport).permit(:domain, :nexthop, :port)
    end
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/_form.html.erb
<%= form_with(model: transport, local: true, class: 'form-horizontal') do |form| %>
  <% if transport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transport.errors.count, "error") %> prohibited this transport from being saved:</h2>

      <ul>
      <% transport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <div class="col-3">
      <%= form.label :domain, class: 'form-label' %>
    </div>
    <div class="col-9">
      <%= form.text_field :domain, class: 'form-input' %>
    </div>
  </div>

  <div class="field form-group">
    <div class="col-3">
      <%= form.label :nexthop, class: 'form-label' %>
    </div>
    <div class="col-9">
      <%= form.text_field :nexthop, class: 'form-input' %>
    </div>
  </div>

  <div class="field form-group">
    <div class="col-3">
      <%= form.label :port, class: 'form-label' %>
    </div>
    <div class="col-9">
      <%= form.number_field :port, class: 'form-input' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/transports/edit.html.erb
<h2>配送先振り分け設定 編集</h2>

<%= render 'form', transport: @transport %>

<%= link_to 'Back', transports_path, class: 'btn' %>

app/views/transports/index.html.erb
<h2>配送先振り分け設定</h2>

<table class="table">
  <thead>
    <tr>
      <th>Domain</th>
      <th>Nexthop</th>
      <th>Port</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @transports.each do |transport| %>
      <tr>
        <td><%= transport.domain %></td>
        <td><%= transport.nexthop %></td>
        <td><%= transport.port %></td>
        <td><%= link_to 'Edit', edit_transport_path(transport), class: 'btn' %></td>
        <td><%= link_to 'Destroy', transport, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-error' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transport', new_transport_path, class: 'btn' %>

app/views/transports/new.html.erb
<h2>配送先振り分け設定 新規作成</h2>

<%= render 'form', transport: @transport %>

<%= link_to 'Back', transports_path, class: 'btn' %>