config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :api_access_allowed_ips, except: [:show, :edit, :update]
  resources :transports, except: [:show]
  resources :attachments_encryption_disable_domain_tos, except: [:show]
  resources :attachments_encryption_disable_domain_froms, except: [:show]
  resources :attachments_encryption_disable_emails, except: [:show]
  resources :bcc_conversion_disable_domains, except: [:show]
  root to: 'settings#index'
  resources :settings, only: [:create]
  get '/api/v1/setting.json', to: 'settings#index_api_v1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attachments_encryption_disable_domain_from.rb
class AttachmentsEncryptionDisableDomainFrom < ApplicationRecord
  belongs_to :setting
end

app/controllers/attachments_encryption_disable_domain_froms_controller.rb
class AttachmentsEncryptionDisableDomainFromsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attachments_encryption_disable_domain_from, only: [:show, :edit, :update, :destroy]

  # GET /attachments_encryption_disable_domain_froms
  # GET /attachments_encryption_disable_domain_froms.json
  def index
    @attachments_encryption_disable_domain_froms = Setting.current.attachments_encryption_disable_domain_froms
  end

  # GET /attachments_encryption_disable_domain_froms/new
  def new
    @attachments_encryption_disable_domain_from = Setting.current.attachments_encryption_disable_domain_froms.build
  end

  # GET /attachments_encryption_disable_domain_froms/1/edit
  def edit
  end

  # POST /attachments_encryption_disable_domain_froms
  # POST /attachments_encryption_disable_domain_froms.json
  def create
    @attachments_encryption_disable_domain_from = Setting.current.attachments_encryption_disable_domain_froms.build(attachments_encryption_disable_domain_from_params)

    respond_to do |format|
      if @attachments_encryption_disable_domain_from.save
        format.html { redirect_to attachments_encryption_disable_domain_froms_url, notice: 'Attachments encryption disable domain from was successfully created.' }
        format.json { render :show, status: :created, location: @attachments_encryption_disable_domain_from }
      else
        format.html { render :new }
        format.json { render json: @attachments_encryption_disable_domain_from.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments_encryption_disable_domain_froms/1
  # PATCH/PUT /attachments_encryption_disable_domain_froms/1.json
  def update
    respond_to do |format|
      if @attachments_encryption_disable_domain_from.update(attachments_encryption_disable_domain_from_params)
        format.html { redirect_to attachments_encryption_disable_domain_froms_url, notice: 'Attachments encryption disable domain from was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachments_encryption_disable_domain_from }
      else
        format.html { render :edit }
        format.json { render json: @attachments_encryption_disable_domain_from.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments_encryption_disable_domain_froms/1
  # DELETE /attachments_encryption_disable_domain_froms/1.json
  def destroy
    @attachments_encryption_disable_domain_from.destroy
    respond_to do |format|
      format.html { redirect_to attachments_encryption_disable_domain_froms_url, notice: 'Attachments encryption disable domain from was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachments_encryption_disable_domain_from
      @attachments_encryption_disable_domain_from = AttachmentsEncryptionDisableDomainFrom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachments_encryption_disable_domain_from_params
      params.require(:attachments_encryption_disable_domain_from).permit(:domain)
    end
end

app/helpers/attachments_encryption_disable_domain_froms_helper.rb
module AttachmentsEncryptionDisableDomainFromsHelper
end

app/views/attachments_encryption_disable_domain_froms/_form.html.erb
<%= form_with(model: attachments_encryption_disable_domain_from, local: true, class: 'form-horizontal') do |form| %>
  <% if attachments_encryption_disable_domain_from.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachments_encryption_disable_domain_from.errors.count, "error") %> prohibited this attachments_encryption_disable_domain_from from being saved:</h2>

      <ul>
      <% attachments_encryption_disable_domain_from.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <div class="col-3">
      <%= form.label :domain, class: 'form-label' %>
    </div>
    <div class="col-9">
      <%= form.text_field :domain, class: 'form-input' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/attachments_encryption_disable_domain_froms/edit.html.erb
<h2>添付ファイル暗号化無効送信元ドメイン 編集</h2>

<%= render 'form', attachments_encryption_disable_domain_from: @attachments_encryption_disable_domain_from %>

<%= link_to 'Back', attachments_encryption_disable_domain_froms_path, class: 'btn' %>

app/views/attachments_encryption_disable_domain_froms/index.html.erb
<h2>添付ファイル暗号化無効送信元ドメイン</h2>

<table class="table">
  <thead>
    <tr>
      <th>Domain</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments_encryption_disable_domain_froms.each do |attachments_encryption_disable_domain_from| %>
      <tr>
        <td><%= attachments_encryption_disable_domain_from.domain %></td>
        <td><%= link_to 'Edit', edit_attachments_encryption_disable_domain_from_path(attachments_encryption_disable_domain_from), class: 'btn' %></td>
        <td><%= link_to 'Destroy', attachments_encryption_disable_domain_from, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-error' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New', new_attachments_encryption_disable_domain_from_path, class: 'btn' %>

app/views/attachments_encryption_disable_domain_froms/new.html.erb
<h2>添付ファイル暗号化無効送信元ドメイン 新規作成</h2>

<%= render 'form', attachments_encryption_disable_domain_from: @attachments_encryption_disable_domain_from %>

<%= link_to 'Back', attachments_encryption_disable_domain_froms_path, class: 'btn' %>